"""empty message

Revision ID: 48c0a42e579a
Revises: dcc3493153e8
Create Date: 2019-02-27 09:57:30.939556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c0a42e579a'
down_revision = 'dcc3493153e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('type_', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'type_')
    # ### end Alembic commands ###
