"""empty message

Revision ID: c2ed97ad1cc5
Revises: 48c0a42e579a
Create Date: 2019-02-28 11:01:32.599661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ed97ad1cc5'
down_revision = '48c0a42e579a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lesson', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lesson')
    # ### end Alembic commands ###
