"""empty message

Revision ID: d03209c2f8f2
Revises: 4b6b10bbe9f3
Create Date: 2019-03-12 11:01:12.582929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd03209c2f8f2'
down_revision = '4b6b10bbe9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'number')
    op.add_column('user', sa.Column('newnumber', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'newnumber')
    op.add_column('news', sa.Column('number', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
