"""empty message

Revision ID: d65d4193fab9
Revises: 2983da5acbd1
Create Date: 2019-03-08 13:47:49.745155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65d4193fab9'
down_revision = '2983da5acbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('taskno', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'taskno')
    # ### end Alembic commands ###
